name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Linux)
        run: python setup.py develop

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Linux)
        run: python -m unittest discover -s tests

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Print installed packages
        run: pip list

      - name: Set up project (macOS)
        run: python setup.py develop

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (macOS)
        run: python -m unittest discover -s tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Windows)
        run: python setup.py develop

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Windows)
        run: python -m unittest discover -s tests


