name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project
        run: |
          echo "PYTHONPATH=$(python -c 'import os; print(os.path.abspath(os.path.join(os.getcwd(), \"..\")))')" >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Linux)
        run: python -m unittest discover -s tests

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project
        run: |
          echo "PYTHONPATH=$(python -c 'import os; print(os.path.abspath(os.path.join(os.getcwd(), \"..\")))')" >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (macOS)
        run: python -m unittest discover -s tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project
        run: |
          echo "::set-env name=PYTHONPATH::$(python -c 'import os; print(os.path.abspath(os.path.join(os.getcwd(), \"..\")))')"

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Windows)
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: python -m unittest discover -s tests
