name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Linux)
        run: echo "PYTHONPATH=${{ github.workspace }}/.." >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Linux)
        run: python -m unittest discover -s tests

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (macOS)
        run: echo "PYTHONPATH=${{ github.workspace }}/.." >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (macOS)
        run: python -m unittest discover -s tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Windows)
        run: |
          echo "Setting PYTHONPATH..."
          echo "Original Content of PYTHONPATH:"
          echo ${PYTHONPATH}
          echo "Original Content of GITHUB ENV:"
          echo ${env:GITHUB_ENV}
          echo "PYTHONPATH=${{ github.workspace }}\\.." >> ${env:GITHUB_ENV}
          echo "Content of GITHUB ENV after adding workspace parent:"
          echo ${env:GITHUB_ENV}
          echo "Now setting the PYTHONPATH variable to:"
          echo ${env:PYTHONPATH}.replace('/', '\\')"
          echo "PYTHONPATH=${env:PYTHONPATH}.replace('/', '\\')" >> ${env:GITHUB_ENV}
          echo "Content of GITHUB ENV after adding workspace parent with replaced slashes:"
          echo ${env:GITHUB_ENV}
          echo "Now trying to get the content with cat in case echo didnt work"
          cat ${env:GITHUB_ENV}

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Windows)
        run: python -m unittest discover -s tests


