name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Linux)
        run: echo "PYTHONPATH=${{ github.workspace }}/.." >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Linux)
        run: python -m unittest discover -s tests

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (macOS)
        run: echo "PYTHONPATH=${{ github.workspace }}/.." >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (macOS)
        run: python -m unittest discover -s tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up project (Windows)
        run: |
          echo "Setting PYTHONPATH..."
          echo "Original PYTHONPATH: $PYTHONPATH"
          echo "Original PYTHONPATH (replacing forward slashes with backslashes): $PYTHONPATH".replace("/", "\\")
          echo "Setting modified PYTHONPATH..."
          echo "PYTHONPATH=${{ github.workspace }}\\.." >> $GITHUB_ENV
          echo "Modified PYTHONPATH: ${{ github.workspace }}\\.."
          echo "Modified PYTHONPATH (replacing forward slashes with backslashes): ${{ github.workspace }}\\..".replace("/", "\\")
          echo "PYTHONPATH set successfully."
          echo "Content of $GITHUB_ENV:"
          cat $GITHUB_ENV

      - name: Run Flake8
        run: flake8 --max-line-length=99

      - name: Run isort
        run: isort .

      - name: Run tests (Windows)
        run: python -m unittest discover -s tests


